<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">

    <form method="POST" action="<?= BASE_URL ?>auth">
        <div class="form-group">
            <label for="usuario">Usuario</label>
            <input type="text" required class="form-control" id="usuario" name="usuario" aria-describedby="usuarioHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>