<?php require 'templates/header.phtml' ?>



<ul class="list-group">
    <?php foreach ($piezas as $pieza): ?>
        <li class="list-group-item">
            <div>
                <a href="piezas/<?= $pieza->id ?>"><b><?= $pieza->titulo ?></b></a>
                | <?= substr($pieza->descripcion, 0, 50) ?> | <?= $pieza->materiales ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> piezas</small></p>

<nav class="mt-4">
    <ul class="pagination">
        <?php for ($i = 1; $i <= $pages; $i++): ?>
            <li class="page-item <?= $i == $page ? 'active' : '' ?>">
                <a class="page-link" href="piezas?page=<?= $i ?>"><?= $i ?></a>
            </li>
        <?php endfor ?>
    </ul>
</nav>

<?php require 'templates/footer.phtml' ?>